[build]
  publish = "dist/Hotel/browser"  # Adjust the path if your project name is different
  command = "npx ng build --configuration production"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
