[build]
  publish = "dist/hotel"  # Adjust the path if your project name is different
  command = "ng build --configuration production"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
